### PR TITLE
Follow sbt plugin best practices

### PR DESCRIPTION
**Pull request by RustedBones**
This PR tries to bring  the [plugin best practices](https://www.scala-sbt.org/1.x/docs/Plugins-Best-Practices.html#Plugins+Best+Practices) to the `sbt-avro` plugin.

It also tries to fix the 'missusage'  of the `AvroConfig` in the plugin:
- Having an `avro` config would normally mean to have a different file mapping. Indeed, configs have their own folder: `Compile` -> `src/main`, `Test` -> `src/test`, `It` -> `src/it`, ...
It is now very difficult to compile avro schema for tests only.
The generate task should be scoped inside the configurations.

- Setting the `version` in `AvroConfig` is abusing the `version` setting from sbt. It is supposed to represent the version of the module, thus of the artifacts produced by this config. Here we just want to reference the avro version used for schema generation.

All those above comments are also valid for `sbt-protobuf`

### CODE REVIEW

**Comment by nevillelyh** [comment]
Sorry totally forgot about this. Will look.

- I'm fine with dropping sbt 0.13 support.
- Right now we have a [avro1.8](https://github.com/sbt/sbt-avro/tree/avro1.8) branch since we still use that internally. Can we consolidate the 2 and make it configurable?
- This is a pretty big breaking change. Should we merge to a branch for now and merge to master when the above points are addressed?

**Comment by RustedBones** [comment]
> I'm fine with dropping sbt 0.13 support.

:heavy_check_mark: 

> Right now we have a avro1.8 branch since we still use that internally. Can we consolidate the 2 and make it configurable?

I'm proposing the following option: setting the `avro-compiler` on plugin definition. Users will have to set the avro version twice: in `project/plugins.sbt` and in `build.sbt`.
This makes the assumption that avro is not breaking API on the compiler between minors. I think it is relatively safe.

> This is a pretty big breaking change. Should we merge to a branch for now and merge to master when the above points are addressed?

I'm fine with it. I have some other ideas to improve packaging and libraries dependencies. Having the code merged into a branch facilitate the development of new features

**Comment by nevillelyh** [comment]
Merged into `v2` branch. I'll play with it a bit and come back if any more Qs. Thanks!

**Comment by nevillelyh** [comment]
A couple of things:
- I added back `libraryDependencies += "org.apache.avro" % "avro-compiler" % "1.9.2"` so it's the default. Users can override with `dependencyOverrides +=` in `plugins.sbt`
- The setting key `avroVersion` conflicts with the `val avroVersion = "1.8.2"` in a lot of our `"org.apache.avro" % "avro" % avroVersion`. What do you think about renaming it, maybe to `sbtAvroVersion`?

**Comment by nevillelyh** [comment]
~Actually we can probably remove the `avroVersion` key, and just infer from `dependencyOverrides += "org.apache.org" % "avro-compiler" % $VERSION` or default to "1.9.2".~

EDIT: it's not that straightforward, seems like I need a way to propagate a string "version" from `plugins.sbt` to the plugin itself.

**Comment by nevillelyh** [comment]
@RustedBones we decided to rename `avroVersion` to `avroLibVersion` to call it a day :joy:
So we can have something like this:
```
val avroVersion = "1.9.2"

avroLibVersion := avroVersion
```

Also ran into some issues publishing to bintry, will try to sort it out soon. :crossed_fingers:

**Comment by nevillelyh** [comment]
And it's now released.

**Comment by RustedBones** [comment]
Thanks a lot @nevillelyh !

By seeing the issue you faced, I'm now questioning the existence of the `avroLibVersion` settings. Its sole purpose is to alter the classpath by adding the default avro library.

We could have let the user specify compiler and library versions explicitly. As a bonus, the plugin would not have to be updated after new version of avro being released.

Maybe for later :)

**Comment by nevillelyh** [comment]
@RustedBones moving the version discussion to https://github.com/sbt/sbt-avro/issues/19 let me know if you have any ideas.

**Pull request merged**
