### PR TITLE
Respect avroSettings for .avpr and .avsc

### LINKED ISSUE #37: field visibility for AVSC source files
Setting the parameter "fieldVisibility" is only possible for AVDL-files. Can you add this for AVSC-files as well?

### LINKED ISSUE #39: stringType and fieldVisibility not respected for protocols

### PR DESCRIPTION
**Pull request by samschlegel**
Fixes #37 and fixes #39

### CODE REVIEW

**Comment by samschlegel** [comment]
Was there a reason this wasn't done before?

**Comment by benmccann** [comment]
Can you add a test?

**Comment by samschlegel** [comment]
Will need to make `SbtAvro#compile` a public method in order to do that, but definitely can

**Comment by benmccann** [comment]
Or it could be a scripted test. I think that's what most of the others are

**Comment by samschlegel** [comment]
Ah right, that could work. I could drop the changes I just made then, but I think they still help with clarity

**Comment by benmccann** [comment]
Thanks!

**Pull request merged**
