### PR TITLE
Pass name to scripted test, fixes broken scripted test

### PR DESCRIPTION
**Pull request by Philippus**
Maybe better to not include the version number in the name of the plugin though.

### CODE REVIEW

**Comment by benmccann** [comment]
I'm going to close and reopen this to see if it'll build it on Travis

**Comment by Philippus** [comment]
Yes, it works!

**Comment by benmccann** [comment]
Yes! Thanks!!

**Comment by benmccann** [comment]
Btw, Avro version number was included on purpose because different people use different versions of Avro and that was the only way to support them all

**Pull request merged**
